window.PATTERN_LIST = [
  { name: "도안1", src: "./도안/도안1.png" },
  { name: "도안2", src: "./도안/도안2.png" },
  { name: "도안3", src: "./도안/도안3.png" },
  { name: "도안4", src: "./도안/도안4.png" },
  { name: "도안5", src: "./도안/도안5.png" },
  { name: "도안6", src: "./도안/도안6.png" },
  { name: "도안7", src: "./도안/도안7.png" },
  { name: "도안8", src: "./도안/도안8.png" },
  { name: "도안9", src: "./도안/도안9.png" },
  { name: "도안10", src: "./도안/도안10.png" },
  { name: "도안11", src: "./도안/도안11.png" },
  { name: "도안12", src: "./도안/도안12.png" },
  { name: "도안13", src: "./도안/도안13.png" },
  { name: "도안14", src: "./도안/도안14.png" },
  { name: "도안15", src: "./도안/도안15.png" },
  { name: "도안16", src: "./도안/도안16.png" },
  { name: "도안17", src: "./도안/도안17.png" },
  { name: "도안18", src: "./도안/도안18.png" },
  { name: "도안19", src: "./도안/도안19.png" },
];
